version: "3.3"

services:
  mongo:
    image: mongo
    volumes:
      - data:/opt/mongodb/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: mongo
    ports:
      - "27017:27017"

volumes:
  data: {}